export const products = [
  {
    id: 1,
    title: "iPhone 16 Pro",
    category: "Smartphones",
    brand: "Apple",
    image: "/products/iphone.jpg",
    price: 129999,
    originalPrice: 139999,
    rating: 4.9,
    reviews: 124,
    badge: "Trending",
    collection: "trending",
  },
  {
    id: 2,
    title: "Nike Air Max",
    category: "Footwear",
    brand: "Nike",
    image: "/products/shoes.jpg",
    price: 8999,
    originalPrice: 9999,
    rating: 4.8,
    reviews: 83,
    badge: "New",
    collection: "new-arrivals",
  },
  {
    id: 3,
    title: "Sony WH-1000XM5",
    category: "Audio",
    brand: "Sony",
    image: "/products/headphones.jpg",
    price: 24999,
    originalPrice: 28999,
    rating: 4.9,
    reviews: 203,
    badge: "Flash Deal",
    collection: "flash-deals",
  },
];